apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-etcd1-d347a1e3-0
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
  storageClassName: local-path
  volumeMode: Filesystem
